// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-ws/wsgateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: wsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: helloHandler(serverCtx),
			},
		},
	)
}
